### ISSUE TITLE
ToolTip Typo

### ISSUE THREAD

**Issue by denpalrius** [denpalrius/Material-Message-Box#1]
[Copied from Reddit Comments](https://www.reddit.com/r/csharp/comments/4zi6k9/a_reusable_material_design_message_box_for_wpf/)

> You have a typo in your ToolTip for the "copy to clipboard" button:
> `ToolTip="Copy to clipbopard"`
> Maybe make that message dynamic as well, for us non-english speakers?

**Comment by Truebamateo** [comment]
It will be a good idea.
Spanish: "Copiar al portapapeles"
