### ISSUE TITLE
Button "Copy to Clipboard"

### ISSUE THREAD

**Issue by Torchok19081986** [denpalrius/Material-Message-Box#10]
Hallo, i create custommessagebox  with my choosed colors. How do i set visibility button "Copy to Clipboard" in messagebox to none visibly. There is no button for change in custommaterialmessagebox class to change it or do i need to override default style ?

**Comment by hubertkrzepkowski** [comment]
var msgerror = new CustomMaterialMessageBox
                    {
                        TxtMessage = { Text = "SQL ERROR : " + error , Foreground = Brushes.White },
                        TxtTitle = { Text = "SQL ERROR", Foreground = Brushes.White },
                        BtnCancel = { Content = "OK", Background = Brushes.Gray, BorderBrush = Brushes.Gray },
                        BtnOk = {Visibility = Visibility.Hidden },
                        MainContentControl = { Background = Brushes.Gray },
                        TitleBackgroundPanel = { Background = Brushes.Red },
                        **BtnCopyMessage ={ Visibility =Visibility.Hidden},**
                        BorderBrush = Brushes.Red
                       };

**Comment by denpalrius** [comment]
Thanks for the suggestion @hubertkrzepkowski 

I updated your solution so that you can still use the 'OK' button and receive results as expected.

 ``` C#
CustomMaterialMessageBox msgerror = new CustomMaterialMessageBox
  {
      Title = "SQL ERROR",
      TxtTitle = { Text = "SQL ERROR", Foreground = Brushes.White },
      TxtMessage = { Text = "SQL ERROR : " + "SQL has issues", Foreground = Brushes.White },
      BtnOk = { Content = "OK", Background = Brushes.Gray, BorderBrush = Brushes.Gray },
      BtnCancel = { Visibility = Visibility.Hidden, Width = 0, Margin = new Thickness(24, 5, -24, 5) },
      MainContentControl = { Background = Brushes.Gray },
      TitleBackgroundPanel = { Background = Brushes.Red },
      BtnCopyMessage = { Visibility = Visibility.Hidden },
      BorderBrush = Brushes.Red
  };

  msgerror.Show();
  MessageBoxResult results = msgerror.Result;
```

I also made the custom message default visibility to false for others to find it more easily.
