### ISSUE TITLE
Custom Message box buttons

### ISSUE THREAD

**Issue by jeranio** [denpalrius/Material-Message-Box#11]
var msg = new CustomMaterialMessageBox
            {
                TxtMessage = { Text = _Message, Foreground =  Brushes.White},
                TxtTitle = { Text = _Title, Foreground = Brushes.White },
                BtnOk = { Content = "OK" },
                MainContentControl = { Background = myBackBrush },
                TitleBackgroundPanel = { Background = myTitleBrush },
                BorderBrush = Brushes.White
            };

This code still produces a cancel button yet the button is not defined.

**Comment by hubertkrzepkowski** [comment]
BtnCancel = { Visibility = Visibility.Hidden },
