### ISSUE TITLE
Exception thrown: 'System.Windows.Markup.XamlParseException' in PresentationFramework.dll The method or operation is not implemented.

### ISSUE THREAD

**Issue by abdou31** [denpalrius/Material-Message-Box#14]
Hello, I have got a bug when I have used the Material MessageBox .
Can you tell me how can I fix this error.

> Exception thrown: 'System.Windows.Markup.XamlParseException' in PresentationFramework.dll
The method or operation is not implemented.

**Comment by denpalrius** [comment]
Hi @abdou31 this could be an issue with the way you have referenced some of the packages you have used in your project.
