### ISSUE TITLE
Mahapps.Metro out date 

### ISSUE THREAD

**Issue by haftado3** [denpalrius/Material-Message-Box#9]
System.IO.FileLoadException: 'Could not load file or assembly 'MahApps.Metro, Version=1.2.4.0, Culture=neutral, PublicKeyToken=f4fb5a3c4d1e5b4f' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

**Comment by Gigas002** [comment]
Just remove the nuget package, download the current repository, then rebuild the project with newest libs from nuget and reference to the BespokeFusion.dll directly. Worked for me.

**Comment by ahmedflix25** [comment]
just while installing ignore dependencies and it will work no questions asked the nuget package just need an update the library itself works https://imgur.com/NgNQunt
